In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [ ]:
df = sns.load_dataset('iris')

In [ ]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [ ]:
from sklearn.model_selection import train_test_split

X = df.drop('species', axis=1)
y = df['species']

In [ ]:
X_train, X_test,y_train, y_test = train_test_split(X,y, test_size=0.33, random_state=42)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
model_knn = KNeighborsClassifier(n_neighbors=11)
model_knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=11)

In [ ]:
model_knn.score(X_test, y_test)

1.0

In [ ]:
from sklearn.svm import SVC
model_svm = SVC(C = 30, kernel='rbf', gamma='auto') # Changing the value of these hyperparameters will result in Score change,Example:  C=10 or 20, or kernel ="linear", etc.
model_svm.fit(X_train, y_train)

SVC(C=30, gamma='auto')

In [ ]:
model_svm.score(X_test, y_test)

0.98

In [ ]:
#Now lets use the GRID SEARCH CV

In [ ]:
from sklearn.model_selection import GridSearchCV

classifier = GridSearchCV((model_svm),{
    'C':[1,10,20,30],
    'kernel':['rbf','linear']
}, cv = 5, return_train_score=False)

classifier.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=SVC(C=30, gamma='auto'),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['rbf', 'linear']})

In [ ]:
classifier.cv_results_

{'mean_fit_time': array([0.00901351, 0.00633721, 0.0056819 , 0.00369558, 0.0046855 ,
        0.00908775, 0.00650072, 0.00486002]),
 'std_fit_time': array([0.00286758, 0.00322587, 0.00270448, 0.00018253, 0.00185417,
        0.00416238, 0.00311438, 0.00171291]),
 'mean_score_time': array([0.00819201, 0.00339422, 0.00309319, 0.00284796, 0.0031395 ,
        0.00546751, 0.0051692 , 0.00435691]),
 'std_score_time': array([0.0053675 , 0.00081495, 0.00044461, 0.00030845, 0.00046813,
        0.00161469, 0.00201137, 0.00283231]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'}],
 'split0_test_score': array([0.95, 1.  , 0.95, 0.95, 0.95, 0.95, 0.95, 0.95]),
 'split1_test_score': array([0.9 , 0.9 , 0.8 , 0.85, 0.8 , 0.85, 0.8 , 0.85]),
 'split2_test_score': array([0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9]),
 'split3_test_score': array([1.  , 1.  , 1.  , 1.  , 1.  , 0.95, 1.  , 1.  ]),
 'split4_test_score': array([0.95, 0.95, 1.  , 0.95, 0.95, 1.  , 1.  , 1.  ]),
 'mean_test_score': array([0.94, 0.95, 0.93, 0.93, 0.92, 0.93, 0.93, 0.94]),
 'std_test_score': array([0.03741657, 0.04472136, 0.07483315, 0.0509902 , 0.0678233 ,
        0.0509902 , 0.07483315, 0.05830952]),
 'rank_test_score': array([2, 1, 4, 6, 8, 6, 4, 3], dtype=int32)}

In [ ]:
result = pd.DataFrame(classifier.cv_results_)
result

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.009014,0.002868,0.008192,0.005368,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.95,0.90,0.9,1.00,0.95,0.94,0.037417,2
1,0.006337,0.003226,0.003394,0.000815,1,linear,"{'C': 1, 'kernel': 'linear'}",1.00,0.90,0.9,1.00,0.95,0.95,0.044721,1
2,0.005682,0.002704,0.003093,0.000445,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.95,0.80,0.9,1.00,1.00,0.93,0.074833,4
3,0.003696,0.000183,0.002848,0.000308,10,linear,"{'C': 10, 'kernel': 'linear'}",0.95,0.85,0.9,1.00,0.95,0.93,0.050990,6
4,0.004685,0.001854,0.003139,0.000468,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.95,0.80,0.9,1.00,0.95,0.92,0.067823,8
5,0.009088,0.004162,0.005468,0.001615,20,linear,"{'C': 20, 'kernel': 'linear'}",0.95,0.85,0.9,0.95,1.00,0.93,0.050990,6
6,0.006501,0.003114,0.005169,0.002011,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.95,0.80,0.9,1.00,1.00,0.93,0.074833,4
7,0.004860,0.001713,0.004357,0.002832,30,linear,"{'C': 30, 'kernel': 'linear'}",0.95,0.85,0.9,1.00,1.00,0.94,0.058310,3

In [ ]:
result[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf             0.94
1        1       linear             0.95
2       10          rbf             0.93
3       10       linear             0.93
4       20          rbf             0.92
5       20       linear             0.93
6       30          rbf             0.93
7       30       linear             0.94

In [ ]:
# Random Search CV

In [ ]:
from sklearn.model_selection import RandomizedSearchCV

classifier_r = RandomizedSearchCV((model_svm),{
    'C':[1,10,20,30],
    'kernel':['rbf','linear']
},n_iter = 4, cv = 5, return_train_score=False)

classifier_r.fit(X_train, y_train)

RandomizedSearchCV(cv=5, estimator=SVC(C=30, gamma='auto'), n_iter=4,
                   param_distributions={'C': [1, 10, 20, 30],
                                        'kernel': ['rbf', 'linear']})

In [ ]:
results = pd.DataFrame(classifier_r.cv_results_)
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_kernel,param_C,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.007692,0.002768,0.007856,0.003120,rbf,1,"{'kernel': 'rbf', 'C': 1}",0.95,0.90,0.9,1.0,0.95,0.94,0.037417,2
1,0.011348,0.006903,0.005866,0.003845,linear,1,"{'kernel': 'linear', 'C': 1}",1.00,0.90,0.9,1.0,0.95,0.95,0.044721,1
2,0.006952,0.006754,0.002865,0.000862,linear,10,"{'kernel': 'linear', 'C': 10}",0.95,0.85,0.9,1.0,0.95,0.93,0.050990,4
3,0.003323,0.000194,0.002657,0.000323,rbf,30,"{'kernel': 'rbf', 'C': 30}",0.95,0.80,0.9,1.0,1.00,0.93,0.074833,3

In [ ]:
results[['param_C','param_kernel','mean_test_score','mean_test_score']]

   param_C param_kernel  mean_test_score  mean_test_score
0        1          rbf             0.94             0.94
1        1       linear             0.95             0.95
2       10       linear             0.93             0.93
3       30          rbf             0.93             0.93